# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8de4d04fb100597df8a89b1e36cc0b19197b3ec39e207f5162d66e978b38d57138e41c170100086f5763d473bf24693ee61f1dad5fb05949fa4b478514f5788f

test:
  secret_key_base: 819df41ac54ef077d5a0157c9f3bc4b52fe618efd7f52962dac31a52112bb91f774ea00b69a11a3d8cbf835a5ea8414632e3934712f2ddb737f8b961d402e21d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
